# Generated by Django 3.2.13 on 2022-06-04 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatechatroom',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='privatechatroom',
            name='user2',
        ),
        migrations.AddField(
            model_name='privatechatroom',
            name='titel',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='ChatRoomUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatRoom', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
