# Generated by Django 3.2.13 on 2022-06-04 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20220605_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroomusers',
            name='chatRoom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatRoom', to='chat.privatechatroom'),
        ),
    ]
